### ISSUE TITLE
Support for Arabic Language RTL

### ISSUE THREAD

**Issue by raddah** [vinkas0/discourse-navigation#11]
I will try to add Arabic Language for this plugin.

<img width="1097" alt="screen shot 2017-08-01 at 8 13 31 pm" src="https://user-images.githubusercontent.com/7273511/28837611-160553d6-76f6-11e7-8adf-826aa1daf45e.png">

**Comment by vinothkannans** [comment]
Thanks for your contribution. You PR https://github.com/VinkasHQ/discourse-navigation/pull/12 is merged now :+1:
